CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	name VARCHAR UNIQUE NOT NULL,
	password VARCHAR NOT NULL,
	email VARCHAR NOT NULL,
	token VARCHAR,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);

CREATE INDEX IF NOT EXISTS idx_users_name on users(name);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
