CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	name VARCHAR UNIQUE NOT NULL,
	password VARCHAR NOT NULL,
	email VARCHAR NOT NULL,
	token VARCHAR,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);
